run:
  timeout: 1m
  tests: true
  go: '1.18'
  show-stats: true

linters:
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
#    - asasalint
#    - asciicheck
#    - bidichk
#    - bodyclose
#    - containedctx
#    - contextcheck
#    - copyloopvar
#    - cyclop
    - deadcode
#    - decorder
#    - depguard
#    - dogsled
#    - dupl
#    - dupword
#    - durationcheck
#    - errcheck
#    - errchkjson
#    - errname
#    - errorlint
#    - execinquery
#    - exhaustive
    - exhaustivestruct
    - exhaustruct
#    - exportloopref
#    - forbidigo
#    - forcetypeassert
    - funlen
#    - gci
#    - ginkgolinter
#    - gocheckcompilerdirectives
#    - gochecknoglobals
#    - gochecknoinits
#    - gochecksumtype
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
    - godot
#    - godox
    - goerr113
#    - gofmt
#    - gofumpt
#    - goheader
#    - goimports
    - golint
#    - gomnd
#    - gomoddirectives
#    - gomodguard
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - gosmopolitan
#    - govet
#    - grouper
    - ifshort
#    - importas
#    - inamedparam
#    - ineffassign
#    - interfacebloat
    - interfacer
#    - intrange
#    - ireturn
    - lll
#    - loggercheck
#    - maintidx
#    - makezero
    - maligned
#    - mirror
#    - misspell
#    - musttag
#    - nakedret
#    - nestif
#    - nilerr
#    - nilnil
    - nlreturn
#    - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
#    - nosprintfhostport
#    - paralleltest
    - perfsprint
#    - prealloc
#    - predeclared
#    - promlinter
#    - protogetter
#    - reassign
#    - revive
#    - rowserrcheck
    - scopelint
#    - sloglint
#    - spancheck
#    - sqlclosecheck
#    - staticcheck
    - structcheck
#    - stylecheck
    - tagalign
#    - tagliatelle
#    - tenv
#    - testableexamples
#    - testifylint
    - testpackage
#    - thelper
#    - tparallel
#    - typecheck
#    - unconvert
    - unparam
#    - unused
#    - usestdlibvars
    - varcheck
    - varnamelen
#    - wastedassign
#    - whitespace
#    - wrapcheck
    - wsl
#    - zerologlint
