name: Review
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.1.5
        with:
          fail_on_error: true
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
